azure:
  free_disk_space: True
  settings_linux:
    swapfile_size: 11GiB
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
