azure:
  free_disk_space: [docker, cache, apt]
  settings_linux:
    swapfile_size: 20GiB
conda_build:
  error_overlinking: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
