azure:
  free_disk_space: [docker, cache, apt]
  settings_linux:
    swapfile_size: 10GiB
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
